server:
  port: 8800
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 查看日志
#  mapper-locations: classpath*:mapper/*.xml
#  type-aliases-package: com.dcz.model
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.1:3306/bibim?characterEncoding=utf-8&useSSL=false
    username: root
    password: ******
  redis:
    host: 192.168.1.1
    port: 6379
    database: 0
    timeout: 1800000
    password: ******
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
#  mvc:
#    servlet:
#      path: /dcz